### ISSUE TITLE
req.host is deprecated in ExpressJS

### ISSUE THREAD

**Issue by patricjansson** [KTH/kth-node-monitor#28]
När jag använder `@kth/monitor` så får jag en varning i loggen.

```bash
express deprecated req.host: Use req.hostname instead at node_modules/@kth/monitor/lib/monitorUtil.js:159:46
```
Jag tittade på koden och det verkar som att ni göra lite regexp som gjorde att det inte bara var att ändra.

**Comment by mast02** [comment]
Det är fixat nu.
